### ISSUE TITLE
Repair script can fail if run on multiple instances with same set of repair targets

### ISSUE THREAD

**Issue by mifisignal** [LeanerCloud/ec2-repair-crowdstrike#2]
The repair script is not safe to run on among multiple instances in an AZ at once. There should be some concurrency control to prevent multiple instances from attempting to perform the repair simultaneously. Consider acquiring a mutex, using some sort of work queue, etc.

**Comment by cristim** [comment]
I'm not so familiar with PowerShell so I may be wrong but I attempted to iterate over the instances in a loop, so they should  not be handled in parallel.

Parallel handling would be difficult because we would have to  use multiple device names and each with its own drive letter.

Again, I have no infrastructure to test this against but my assumption was that the D: drive would be reused for all the volumes.

**Comment by mifisignal** [comment]
By "instances" I mean the instances on which the repair is being performed. If the issue I described in #1 occurs, then the repair instances could end up targeting the same instances simultaneously. IOW the loop variables containing the repair targets will be identical.

**Comment by cristim** [comment]
I see, I now have code that ditches the ASG and creates individual instances, and the Powershell script will terminate the repair instances after it finishes running. 

I also have a test mode that creates a test instance and attempts to run against it.

Now running a few tests against that instance and I'll push the changes as soon as I have it working as expected

**Comment by cristim** [comment]
Resolved, just pushed the code that removes the ASG and uses individual instances.
